# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-cron

frameworkVersion: '3'

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs18.x
  profile: serverless-cli
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: '*'

functions:
  sendReminder:
    handler: src/functions/scheduleTasks/reminderEmail.handler
    events:
      - schedule:
          rate: cron(00 9 ? * 7 *)
  sendMorningNews:
    handler: src/functions/scheduleTasks/morningNews.handler
    events:
      - schedule:
          rate: cron(15 07 ? * * *)
